server:
  port: 8080
  shutdown: graceful
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transferz
    username: postgres
    password: postgres
    driver-class-name:
  jpa:
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  liquibase:
    change-log: /db/changelog/changelog-master.xml

logging:
  level:
    liquibase: INFO

management:
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics'

value:
  amountOfPassengerPerFlight: 150